#ifndef KNX26_CONFIG_H
#define KNX26_CONFIG_H

#include "knx_target_config.h"
#include "knexus_config.h"

#define KNX26_FAST_PERIOD_MS       KNEXUS_FAST_PERIOD_MS
#define KNX26_CONTROL_PERIOD_MS    KNEXUS_CONTROL_PERIOD_MS
#define KNX26_TRACK_PERIOD_MS      KNEXUS_TRACK_PERIOD_MS
#define KNX26_APP_PERIOD_MS        KNEXUS_APP_PERIOD_MS
#define KNX26_PERCEPTION_PERIOD_MS KNEXUS_PERCEPTION_PERIOD_MS
#define KNX26_COMM_PERIOD_MS       KNEXUS_COMM_PERIOD_MS
#define KNX26_DEBUG_PERIOD_MS      KNEXUS_DEBUG_PERIOD_MS
#define KNX26_FAST_PHASE_MS        KNEXUS_FAST_PHASE_MS
#define KNX26_CONTROL_PHASE_MS     KNEXUS_CONTROL_PHASE_MS
#define KNX26_TRACK_PHASE_MS       KNEXUS_TRACK_PHASE_MS
#define KNX26_APP_PHASE_MS         KNEXUS_APP_PHASE_MS
#define KNX26_PERCEPTION_PHASE_MS  KNEXUS_PERCEPTION_PHASE_MS
#define KNX26_COMM_PHASE_MS        KNEXUS_COMM_PHASE_MS
#define KNX26_DEBUG_PHASE_MS       KNEXUS_DEBUG_PHASE_MS
#define KNX26_CAN_HEARTBEAT_MS     KNEXUS_CAN_HEARTBEAT_MS
#define KNX26_LINK_HEARTBEAT_MS    KNEXUS_LINK_HEARTBEAT_MS
#define KNX26_OCTO_BASE            KNEXUS_OCTO_BASE_ID
#define KNX26_OCTO_DEBUG_EN        KNEXUS_DEBUG_OCTOLINK_ENABLE
#define KNX26_INTERSECTION_EN      KNEXUS_INTERSECTION_ENABLE
#define KNX26_H_BALL_PERIOD_MS     KNEXUS_H_BALL_CONTROL_PERIOD_MS

#if (KNX26_FAST_PERIOD_MS == 0U) || (KNX26_CONTROL_PERIOD_MS == 0U) || \
    (KNX26_TRACK_PERIOD_MS == 0U) || (KNX26_APP_PERIOD_MS == 0U) || \
    (KNX26_PERCEPTION_PERIOD_MS == 0U) || \
    (KNX26_COMM_PERIOD_MS == 0U) || (KNX26_DEBUG_PERIOD_MS == 0U)
#error "KNexus: task periods must be greater than zero"
#endif

#if (KNX26_FAST_PHASE_MS >= KNX26_FAST_PERIOD_MS) || \
    (KNX26_CONTROL_PHASE_MS >= KNX26_CONTROL_PERIOD_MS) || \
    (KNX26_TRACK_PHASE_MS >= KNX26_TRACK_PERIOD_MS) || \
    (KNX26_APP_PHASE_MS >= KNX26_APP_PERIOD_MS) || \
    (KNX26_PERCEPTION_PHASE_MS >= KNX26_PERCEPTION_PERIOD_MS) || \
    (KNX26_COMM_PHASE_MS >= KNX26_COMM_PERIOD_MS) || \
    (KNX26_DEBUG_PHASE_MS >= KNX26_DEBUG_PERIOD_MS)
#error "KNexus: each task phase must be smaller than its period"
#endif

#if (defined(KNEXUS_MODE_LINE_FOLLOW) || \
     defined(KNEXUS_MODE_LINE_FOLLOW_BALL_CENTER)) && \
    KNEXUS_H_TASK_ENABLE && \
    (KNX26_H_BALL_PERIOD_MS == 0U)
#error "KNexus: invalid H-problem ball control period"
#endif

/* Set to 1 only for direct KEY0/KEY1 motor-pin probing.  Normal contest
 * firmware uses the KEY0 calibration / KEY1 line-follow workflow. */
#define KNX26_MOTOR_PIN_TEST       0
#define KNX26_MOTOR_PIN_TEST_DUTY  0.0f

#if defined(KNX_PLATFORM_STM32)
#define KNX26_LOCAL_NODE_ID        1U
#define KNX26_ROLE_MAIN_CONTROLLER 1
#else
#define KNX26_LOCAL_NODE_ID        2U
#define KNX26_ROLE_MAIN_CONTROLLER 0
#endif

#endif
