#ifndef KNX_BOARD_CONFIG_H
#define KNX_BOARD_CONFIG_H

/* MSPM0 target marker used by common/User/config/knx_target_config.h. */
#define KNX_TARGET_MSPM0  1

/* Board clock is generated by SysConfig. Keep this value in sync with CPUCLK_FREQ. */
#define KNX_BOARD_CPU_HZ  80000000UL

/*
 * Future SysConfig bindings:
 * - Add UART/CAN/SPI/PWM/ADC instance aliases here after regenerating SysConfig.
 * - Keep common modules using board getters instead of direct SysConfig symbols.
 */

#endif /* KNX_BOARD_CONFIG_H */
