/*
 *  ============ ti_msp_dl_config.c ============
 *  Generated by SysConfig, manually patched:
 *    - 80 MHz HFXT+PLL clock (CANCLK from HFCLK)
 *    - KEY / ENC_R pins as digital input with edge interrupt
 *    - UART baud rate divisors for 80 MHz
 *    - SPI BMI088, MCAN0, BMI CS, track sensor GPIO
 */

#include "ti_msp_dl_config.h"

DL_TimerG_backupConfig gQEI_RIGHTBackup;
DL_TimerA_backupConfig gPWM_LBackup;
DL_TimerA_backupConfig gPWM_RBackup;
DL_UART_Main_backupConfig gUART_DEBUGBackup;
DL_SPI_backupConfig gSPI_BMI088Backup;
DL_MCAN_backupConfig gMCAN0Backup;

volatile uint32_t knx_mspm0_boot_stage = 0U;
volatile uint32_t knx_mspm0_boot_error = 0U;

#define KNX_MSPM0_BOOT_ERR_MCAN_MEM_INIT    (1UL << 0)
#define KNX_MSPM0_BOOT_ERR_MCAN_SW_INIT     (1UL << 1)
#define KNX_MSPM0_BOOT_ERR_MCAN_NORMAL      (1UL << 2)
#define KNX_MSPM0_BOOT_ERR_HFXT_TIMEOUT     (1UL << 3)

static bool knx_wait_mcan_opmode(MCAN_Regs *mcan,
                                 DL_MCAN_OPERATION_MODE mode,
                                 uint32_t limit)
{
    while (DL_MCAN_getOpMode(mcan) != mode) {
        if (limit-- == 0U) {
            return false;
        }
    }
    return true;
}

SYSCONFIG_WEAK void SYSCFG_DL_init(void)
{
    knx_mspm0_boot_stage = 1U;
    SYSCFG_DL_initPower();
    knx_mspm0_boot_stage = 2U;
    SYSCFG_DL_GPIO_init();
    knx_mspm0_boot_stage = 3U;
    SYSCFG_DL_SYSCTL_init();
    knx_mspm0_boot_stage = 4U;
    SYSCFG_DL_QEI_RIGHT_init();
    knx_mspm0_boot_stage = 5U;
    SYSCFG_DL_UART_DEBUG_init();
    knx_mspm0_boot_stage = 6U;
    SYSCFG_DL_PWM_L_init();
    knx_mspm0_boot_stage = 7U;
    SYSCFG_DL_PWM_R_init();
    knx_mspm0_boot_stage = 8U;
    SYSCFG_DL_ADC_MOTOR_init();
    SYSCFG_DL_ADC_TRACK_init();
    knx_mspm0_boot_stage = 9U;
    SYSCFG_DL_SPI_BMI088_init();
    knx_mspm0_boot_stage = 10U;
    SYSCFG_DL_MCAN0_init();
    knx_mspm0_boot_stage = 11U;
    gQEI_RIGHTBackup.backupRdy    = false;
    gPWM_LBackup.backupRdy        = false;
    gPWM_RBackup.backupRdy        = false;
    gUART_DEBUGBackup.backupRdy   = false;
    gSPI_BMI088Backup.backupRdy   = false;
    gMCAN0Backup.backupRdy        = false;
}

SYSCONFIG_WEAK bool SYSCFG_DL_saveConfiguration(void)
{
    bool retStatus = true;
    retStatus &= DL_TimerA_saveConfiguration(PWM_L_INST, &gPWM_LBackup);
    retStatus &= DL_TimerA_saveConfiguration(PWM_R_INST, &gPWM_RBackup);
    retStatus &= DL_TimerG_saveConfiguration(QEI_RIGHT_INST, &gQEI_RIGHTBackup);
    retStatus &= DL_UART_Main_saveConfiguration(UART_DEBUG_INST, &gUART_DEBUGBackup);
    retStatus &= DL_SPI_saveConfiguration(SPI_BMI088_INST, &gSPI_BMI088Backup);
    retStatus &= DL_MCAN_saveConfiguration(MCAN0_INST, &gMCAN0Backup);
    return retStatus;
}

SYSCONFIG_WEAK bool SYSCFG_DL_restoreConfiguration(void)
{
    bool retStatus = true;
    retStatus &= DL_TimerA_restoreConfiguration(PWM_L_INST, &gPWM_LBackup, false);
    retStatus &= DL_TimerA_restoreConfiguration(PWM_R_INST, &gPWM_RBackup, false);
    retStatus &= DL_TimerG_restoreConfiguration(QEI_RIGHT_INST, &gQEI_RIGHTBackup, false);
    retStatus &= DL_UART_Main_restoreConfiguration(UART_DEBUG_INST, &gUART_DEBUGBackup);
    retStatus &= DL_SPI_restoreConfiguration(SPI_BMI088_INST, &gSPI_BMI088Backup);
    retStatus &= DL_MCAN_restoreConfiguration(MCAN0_INST, &gMCAN0Backup);
    return retStatus;
}

SYSCONFIG_WEAK void SYSCFG_DL_initPower(void)
{
    DL_GPIO_reset(GPIOA);
    DL_GPIO_reset(GPIOB);
    DL_TimerG_reset(QEI_RIGHT_INST);
    DL_TimerA_reset(PWM_L_INST);
    DL_TimerA_reset(PWM_R_INST);
    DL_UART_Main_reset(UART_DEBUG_INST);
    DL_ADC12_reset(ADC_MOTOR_INST);
    DL_ADC12_reset(ADC_TRACK_INST);
    DL_SPI_reset(SPI_BMI088_INST);
    DL_MCAN_reset(MCAN0_INST);

    DL_GPIO_enablePower(GPIOA);
    DL_GPIO_enablePower(GPIOB);
    DL_TimerG_enablePower(QEI_RIGHT_INST);
    DL_TimerA_enablePower(PWM_L_INST);
    DL_TimerA_enablePower(PWM_R_INST);
    DL_UART_Main_enablePower(UART_DEBUG_INST);
    DL_ADC12_enablePower(ADC_MOTOR_INST);
    DL_ADC12_enablePower(ADC_TRACK_INST);
    DL_SPI_enablePower(SPI_BMI088_INST);
    DL_MCAN_enablePower(MCAN0_INST);
    delay_cycles(POWER_STARTUP_DELAY);
}

SYSCONFIG_WEAK void SYSCFG_DL_GPIO_init(void)
{
    /* HFXT crystal pins */
    DL_GPIO_initPeripheralAnalogFunction(GPIO_HFXIN_IOMUX);
    DL_GPIO_initPeripheralAnalogFunction(GPIO_HFXOUT_IOMUX);

    /* QEI encoder peripheral inputs */
    DL_GPIO_initPeripheralInputFunction(GPIO_QEI_RIGHT_PHA_IOMUX,
                                        GPIO_QEI_RIGHT_PHA_IOMUX_FUNC);
    DL_GPIO_initPeripheralInputFunction(GPIO_QEI_RIGHT_PHB_IOMUX,
                                        GPIO_QEI_RIGHT_PHB_IOMUX_FUNC);

    /* UART peripheral pins */
    DL_GPIO_initPeripheralOutputFunction(GPIO_UART_DEBUG_IOMUX_TX,
                                         GPIO_UART_DEBUG_IOMUX_TX_FUNC);
    DL_GPIO_initPeripheralInputFunction(GPIO_UART_DEBUG_IOMUX_RX,
                                        GPIO_UART_DEBUG_IOMUX_RX_FUNC);

    /* PWM output pins */
    DL_GPIO_initPeripheralOutputFunction(GPIO_PWM_L_C0_IOMUX,
                                         GPIO_PWM_L_C0_IOMUX_FUNC);
    DL_GPIO_enableOutput(GPIO_PWM_L_C0_PORT, GPIO_PWM_L_C0_PIN);
    DL_GPIO_initPeripheralOutputFunction(GPIO_PWM_HEATER_C2_IOMUX,
                                         GPIO_PWM_HEATER_C2_IOMUX_FUNC);
    DL_GPIO_enableOutput(GPIO_PWM_HEATER_C2_PORT, GPIO_PWM_HEATER_C2_PIN);
    DL_GPIO_initPeripheralOutputFunction(GPIO_PWM_R_C0_IOMUX,
                                         GPIO_PWM_R_C0_IOMUX_FUNC);
    DL_GPIO_enableOutput(GPIO_PWM_R_C0_PORT, GPIO_PWM_R_C0_PIN);

    /* SPI BMI088 peripheral pins */
    DL_GPIO_initPeripheralOutputFunction(GPIO_SPI_BMI088_IOMUX_SCLK,
                                         GPIO_SPI_BMI088_IOMUX_SCLK_FUNC);
    DL_GPIO_initPeripheralOutputFunction(GPIO_SPI_BMI088_IOMUX_PICO,
                                         GPIO_SPI_BMI088_IOMUX_PICO_FUNC);
    DL_GPIO_initPeripheralInputFunction(GPIO_SPI_BMI088_IOMUX_POCI,
                                        GPIO_SPI_BMI088_IOMUX_POCI_FUNC);
    DL_GPIO_initPeripheralOutputFunction(GPIO_SPI_BMI088_IOMUX_CS0,
                                         GPIO_SPI_BMI088_IOMUX_CS0_FUNC);

    /* MCAN peripheral pins */
    DL_GPIO_initPeripheralOutputFunction(GPIO_MCAN0_IOMUX_CAN_TX,
                                         GPIO_MCAN0_IOMUX_CAN_TX_FUNC);
    DL_GPIO_initPeripheralInputFunction(GPIO_MCAN0_IOMUX_CAN_RX,
                                        GPIO_MCAN0_IOMUX_CAN_RX_FUNC);

    /* Motor-current analog input. */
    DL_GPIO_initPeripheralAnalogFunction(GPIO_ADC_MOTOR_C0_IOMUX);

    /* LED outputs */
    DL_GPIO_initDigitalOutput(LED0_LED0_PIN_IOMUX);
    DL_GPIO_initDigitalOutput(LED1_LED1_PIN_IOMUX);
    DL_GPIO_initDigitalOutput(LED2_LED2_PIN_IOMUX);
    DL_GPIO_clearPins(GPIOB, LED0_LED0_PIN_PIN |
                             LED1_LED1_PIN_PIN |
                             LED2_LED2_PIN_PIN);
    DL_GPIO_enableOutput(GPIOB, LED0_LED0_PIN_PIN |
                                 LED1_LED1_PIN_PIN |
                                 LED2_LED2_PIN_PIN);

    /* KEY inputs (pull-down) */
    DL_GPIO_initDigitalInputFeatures(KEY0_KEY0_PIN_IOMUX,
        DL_GPIO_INVERSION_DISABLE, DL_GPIO_RESISTOR_PULL_DOWN,
        DL_GPIO_HYSTERESIS_DISABLE, DL_GPIO_WAKEUP_DISABLE);
    DL_GPIO_initDigitalInputFeatures(KEY1_KEY1_PIN_IOMUX,
        DL_GPIO_INVERSION_DISABLE, DL_GPIO_RESISTOR_PULL_DOWN,
        DL_GPIO_HYSTERESIS_DISABLE, DL_GPIO_WAKEUP_DISABLE);

    /* BEEP output */
    DL_GPIO_initDigitalOutput(BEEP_BEEP0_PIN_IOMUX);
    DL_GPIO_clearPins(GPIOB, BEEP_BEEP0_PIN_PIN);
    DL_GPIO_enableOutput(GPIOB, BEEP_BEEP0_PIN_PIN);

    /* Motor PHASE outputs */
    DL_GPIO_initDigitalOutput(MOTOR_L_PH_ML_PHASE_IOMUX);
    DL_GPIO_initDigitalOutput(MOTOR_R_PH_MR_PHASE_IOMUX);
    DL_GPIO_clearPins(GPIOA, MOTOR_L_PH_ML_PHASE_PIN |
                             MOTOR_R_PH_MR_PHASE_PIN);
    DL_GPIO_enableOutput(GPIOA, MOTOR_L_PH_ML_PHASE_PIN |
                                 MOTOR_R_PH_MR_PHASE_PIN);

    /* Left encoder GPIO inputs (pull-down, both-edge interrupt) */
    DL_GPIO_initDigitalInputFeatures(ENC_RA_ENC_RA_PIN_IOMUX,
        DL_GPIO_INVERSION_DISABLE, DL_GPIO_RESISTOR_PULL_DOWN,
        DL_GPIO_HYSTERESIS_DISABLE, DL_GPIO_WAKEUP_DISABLE);
    DL_GPIO_initDigitalInputFeatures(ENC_RB_ENC_RB_PIN_IOMUX,
        DL_GPIO_INVERSION_DISABLE, DL_GPIO_RESISTOR_PULL_DOWN,
        DL_GPIO_HYSTERESIS_DISABLE, DL_GPIO_WAKEUP_DISABLE);
    DL_GPIO_setLowerPinsPolarity(GPIOA,
        DL_GPIO_PIN_8_EDGE_RISE_FALL | DL_GPIO_PIN_9_EDGE_RISE_FALL);
    DL_GPIO_clearInterruptStatus(GPIOA,
        ENC_RA_ENC_RA_PIN_PIN | ENC_RB_ENC_RB_PIN_PIN);
    DL_GPIO_enableInterrupt(GPIOA,
        ENC_RA_ENC_RA_PIN_PIN | ENC_RB_ENC_RB_PIN_PIN);

    /* BMI chip-select outputs (active-low, default high = deselected) */
    DL_GPIO_initDigitalOutput(BMI_CS0_CS0_PIN_IOMUX);
    DL_GPIO_initDigitalOutput(BMI_CS1_CS1_PIN_IOMUX);
    DL_GPIO_setPins(GPIOA, BMI_CS0_CS0_PIN_PIN | BMI_CS1_CS1_PIN_PIN);
    DL_GPIO_enableOutput(GPIOA, BMI_CS0_CS0_PIN_PIN | BMI_CS1_CS1_PIN_PIN);

    /* Track sensor MUX select outputs */
    DL_GPIO_initDigitalOutput(TRK_AD0_AD0_PIN_IOMUX);
    DL_GPIO_initDigitalOutput(TRK_AD1_AD1_PIN_IOMUX);
    DL_GPIO_initDigitalOutput(TRK_AD2_AD2_PIN_IOMUX);
    DL_GPIO_clearPins(GPIOB, TRK_AD0_AD0_PIN_PIN |
                             TRK_AD1_AD1_PIN_PIN |
                             TRK_AD2_AD2_PIN_PIN);
    DL_GPIO_enableOutput(GPIOB, TRK_AD0_AD0_PIN_PIN |
                                 TRK_AD1_AD1_PIN_PIN |
                                 TRK_AD2_AD2_PIN_PIN);

    /* OLED software-I2C pins idle released; driver toggles DOE as open-drain. */
    DL_GPIO_initDigitalInput(OLED_SCL_SCL_PIN_IOMUX);
    DL_GPIO_initDigitalInput(OLED_SDA_SDA_PIN_IOMUX);
    DL_GPIO_clearPins(GPIOA, OLED_SCL_SCL_PIN_PIN | OLED_SDA_SDA_PIN_PIN);
    DL_GPIO_disableOutput(GPIOA, OLED_SCL_SCL_PIN_PIN | OLED_SDA_SDA_PIN_PIN);
}

/* ── 80 MHz clock (HFXT 40 MHz → SYSPLL → MCLK 80 MHz) ── */
static const DL_SYSCTL_SYSPLLConfig gSYSPLLConfig = {
    .inputFreq   = DL_SYSCTL_SYSPLL_INPUT_FREQ_32_48_MHZ,
    .rDivClk2x   = 1, .rDivClk1 = 0, .rDivClk0 = 0,
    .enableCLK2x = DL_SYSCTL_SYSPLL_CLK2X_DISABLE,
    .enableCLK1  = DL_SYSCTL_SYSPLL_CLK1_DISABLE,
    .enableCLK0  = DL_SYSCTL_SYSPLL_CLK0_ENABLE,
    .sysPLLMCLK  = DL_SYSCTL_SYSPLL_MCLK_CLK0,
    .sysPLLRef   = DL_SYSCTL_SYSPLL_REF_HFCLK,
    .qDiv        = 3,
    .pDiv        = DL_SYSCTL_SYSPLL_PDIV_1
};

SYSCONFIG_WEAK void SYSCFG_DL_SYSCTL_init(void)
{
    DL_SYSCTL_setBORThreshold(DL_SYSCTL_BOR_THRESHOLD_LEVEL_0);
    DL_SYSCTL_setFlashWaitState(DL_SYSCTL_FLASH_WAIT_STATE_2);
    DL_SYSCTL_setSYSOSCFreq(DL_SYSCTL_SYSOSC_FREQ_BASE);

    DL_SYSCTL_setHFCLKSourceHFXTParams(
        DL_SYSCTL_HFXT_RANGE_32_48_MHZ, 10, false);
    DL_SYSCTL_enableHFCLKStartupMonitor();

    uint32_t waitLimit = 1000000U;
    while ((DL_SYSCTL_getClockStatus() & SYSCTL_CLKSTATUS_HFCLKGOOD_MASK) !=
           DL_SYSCTL_CLK_STATUS_HFCLK_GOOD) {
        if (waitLimit-- == 0U) {
            knx_mspm0_boot_error |= KNX_MSPM0_BOOT_ERR_HFXT_TIMEOUT;
            DL_SYSCTL_disableHFCLKStartupMonitor();
            DL_SYSCTL_disableHFXT();
            DL_SYSCTL_setULPCLKDivider(DL_SYSCTL_ULPCLK_DIV_2);
            DL_SYSCTL_enableMFCLK();
            return;
        }
    }

    DL_SYSCTL_configSYSPLL((DL_SYSCTL_SYSPLLConfig *)&gSYSPLLConfig);
    DL_SYSCTL_setULPCLKDivider(DL_SYSCTL_ULPCLK_DIV_2);
    DL_SYSCTL_enableMFCLK();
    DL_SYSCTL_setMCLKSource(SYSOSC, HSCLK, DL_SYSCTL_HSCLK_SOURCE_SYSPLL);
}

/* ── QEI left encoder ── */
static const DL_TimerG_ClockConfig gQEI_RIGHTClockConfig = {
    .clockSel = DL_TIMER_CLOCK_BUSCLK,
    .divideRatio = DL_TIMER_CLOCK_DIVIDE_1,
    .prescale = 0U
};

SYSCONFIG_WEAK void SYSCFG_DL_QEI_RIGHT_init(void)
{
    DL_TimerG_setClockConfig(QEI_RIGHT_INST,
        (DL_TimerG_ClockConfig *)&gQEI_RIGHTClockConfig);
    DL_TimerG_configQEI(QEI_RIGHT_INST, DL_TIMER_QEI_MODE_2_INPUT,
        DL_TIMER_CC_INPUT_INV_NOINVERT, DL_TIMER_CC_0_INDEX);
    DL_TimerG_configQEI(QEI_RIGHT_INST, DL_TIMER_QEI_MODE_2_INPUT,
        DL_TIMER_CC_INPUT_INV_NOINVERT, DL_TIMER_CC_1_INDEX);
    DL_TimerG_setLoadValue(QEI_RIGHT_INST, 65535);
    DL_TimerG_enableClock(QEI_RIGHT_INST);
}

/* ── UART debug ── */
static const DL_UART_Main_ClockConfig gUART_DEBUGClockConfig = {
    .clockSel = DL_UART_MAIN_CLOCK_BUSCLK,
    .divideRatio = DL_UART_MAIN_CLOCK_DIVIDE_RATIO_1
};
static const DL_UART_Main_Config gUART_DEBUGConfig = {
    .mode = DL_UART_MAIN_MODE_NORMAL,
    .direction = DL_UART_MAIN_DIRECTION_TX_RX,
    .flowControl = DL_UART_MAIN_FLOW_CONTROL_NONE,
    .parity = DL_UART_MAIN_PARITY_NONE,
    .wordLength = DL_UART_MAIN_WORD_LENGTH_8_BITS,
    .stopBits = DL_UART_MAIN_STOP_BITS_ONE
};

SYSCONFIG_WEAK void SYSCFG_DL_UART_DEBUG_init(void)
{
    DL_UART_Main_setClockConfig(UART_DEBUG_INST,
        (DL_UART_Main_ClockConfig *)&gUART_DEBUGClockConfig);
    DL_UART_Main_init(UART_DEBUG_INST,
        (DL_UART_Main_Config *)&gUART_DEBUGConfig);
    DL_UART_Main_setOversampling(UART_DEBUG_INST,
        DL_UART_OVERSAMPLING_RATE_16X);
    DL_UART_Main_setBaudRateDivisor(UART_DEBUG_INST,
        UART_DEBUG_IBRD_80_MHZ_921600_BAUD,
        UART_DEBUG_FBRD_80_MHZ_921600_BAUD);
    DL_UART_Main_enable(UART_DEBUG_INST);
}

/* ── PWM left motor (TIMA0, 80 MHz / 1 / 4000 = 20 kHz) ── */
static const DL_TimerA_ClockConfig gPWM_LClockConfig = {
    .clockSel = DL_TIMER_CLOCK_BUSCLK,
    .divideRatio = DL_TIMER_CLOCK_DIVIDE_1,
    .prescale = 0U
};
static const DL_TimerA_PWMConfig gPWM_LConfig = {
    .pwmMode = DL_TIMER_PWM_MODE_EDGE_ALIGN,
    .period = 4000,
    .isTimerWithFourCC = true,
    .startTimer = DL_TIMER_STOP,
};

SYSCONFIG_WEAK void SYSCFG_DL_PWM_L_init(void)
{
    DL_TimerA_setClockConfig(PWM_L_INST,
        (DL_TimerA_ClockConfig *)&gPWM_LClockConfig);
    DL_TimerA_initPWMMode(PWM_L_INST,
        (DL_TimerA_PWMConfig *)&gPWM_LConfig);
    DL_TimerA_setCounterControl(PWM_L_INST,
        DL_TIMER_CZC_CCCTL0_ZCOND,
        DL_TIMER_CAC_CCCTL0_ACOND,
        DL_TIMER_CLC_CCCTL0_LCOND);
    DL_TimerA_setCaptureCompareOutCtl(PWM_L_INST,
        DL_TIMER_CC_OCTL_INIT_VAL_LOW,
        DL_TIMER_CC_OCTL_INV_OUT_DISABLED,
        DL_TIMER_CC_OCTL_SRC_FUNCVAL,
        DL_TIMERA_CAPTURE_COMPARE_0_INDEX);
    DL_TimerA_setCaptCompUpdateMethod(PWM_L_INST,
        DL_TIMER_CC_UPDATE_METHOD_IMMEDIATE,
        DL_TIMERA_CAPTURE_COMPARE_0_INDEX);
    DL_TimerA_setCaptureCompareValue(PWM_L_INST, 4000,
        DL_TIMER_CC_0_INDEX);
    DL_TimerA_setCaptureCompareOutCtl(PWM_L_INST,
        DL_TIMER_CC_OCTL_INIT_VAL_LOW,
        DL_TIMER_CC_OCTL_INV_OUT_DISABLED,
        DL_TIMER_CC_OCTL_SRC_FUNCVAL,
        DL_TIMERA_CAPTURE_COMPARE_1_INDEX);
    DL_TimerA_setCaptCompUpdateMethod(PWM_L_INST,
        DL_TIMER_CC_UPDATE_METHOD_IMMEDIATE,
        DL_TIMERA_CAPTURE_COMPARE_1_INDEX);
    DL_TimerA_setCaptureCompareValue(PWM_L_INST, 4000,
        DL_TIMER_CC_1_INDEX);
    DL_TimerA_setCaptureCompareOutCtl(PWM_L_INST,
        DL_TIMER_CC_OCTL_INIT_VAL_LOW,
        DL_TIMER_CC_OCTL_INV_OUT_DISABLED,
        DL_TIMER_CC_OCTL_SRC_FUNCVAL,
        DL_TIMERA_CAPTURE_COMPARE_2_INDEX);
    DL_TimerA_setCaptCompUpdateMethod(PWM_L_INST,
        DL_TIMER_CC_UPDATE_METHOD_IMMEDIATE,
        DL_TIMERA_CAPTURE_COMPARE_2_INDEX);
    DL_TimerA_setCaptureCompareValue(PWM_L_INST, 4000,
        DL_TIMER_CC_2_INDEX);
    DL_TimerA_setCCPOutputDisabledAdv(PWM_L_INST,
        DL_TIMER_CCP0_DIS_OUT_ADV_FORCE_LOW |
        DL_TIMER_CCP1_DIS_OUT_ADV_FORCE_LOW |
        DL_TIMER_CCP2_DIS_OUT_ADV_FORCE_LOW |
        DL_TIMER_CCP3_DIS_OUT_ADV_FORCE_LOW);
    DL_TimerA_enableClock(PWM_L_INST);
    /* Match TI SysConfig's canonical TIMA0 four-CC setup. */
    DL_TimerA_setCCPDirection(PWM_L_INST,
        DL_TIMER_CC0_OUTPUT | DL_TIMER_CC2_OUTPUT);
}

/* ── PWM right motor (TIMA1, 80 MHz / 1 / 4000 = 20 kHz) ── */
static const DL_TimerA_ClockConfig gPWM_RClockConfig = {
    .clockSel = DL_TIMER_CLOCK_BUSCLK,
    .divideRatio = DL_TIMER_CLOCK_DIVIDE_1,
    .prescale = 0U
};
static const DL_TimerA_PWMConfig gPWM_RConfig = {
    .pwmMode = DL_TIMER_PWM_MODE_EDGE_ALIGN,
    .period = 4000,
    .isTimerWithFourCC = false,
    .startTimer = DL_TIMER_STOP,
};

SYSCONFIG_WEAK void SYSCFG_DL_PWM_R_init(void)
{
    DL_TimerA_setClockConfig(PWM_R_INST,
        (DL_TimerA_ClockConfig *)&gPWM_RClockConfig);
    DL_TimerA_initPWMMode(PWM_R_INST,
        (DL_TimerA_PWMConfig *)&gPWM_RConfig);
    DL_TimerA_setCounterControl(PWM_R_INST,
        DL_TIMER_CZC_CCCTL0_ZCOND,
        DL_TIMER_CAC_CCCTL0_ACOND,
        DL_TIMER_CLC_CCCTL0_LCOND);
    DL_TimerA_setCaptureCompareOutCtl(PWM_R_INST,
        DL_TIMER_CC_OCTL_INIT_VAL_LOW,
        DL_TIMER_CC_OCTL_INV_OUT_DISABLED,
        DL_TIMER_CC_OCTL_SRC_FUNCVAL,
        DL_TIMERA_CAPTURE_COMPARE_0_INDEX);
    DL_TimerA_setCaptCompUpdateMethod(PWM_R_INST,
        DL_TIMER_CC_UPDATE_METHOD_IMMEDIATE,
        DL_TIMERA_CAPTURE_COMPARE_0_INDEX);
    DL_TimerA_setCaptureCompareValue(PWM_R_INST, 4000,
        DL_TIMER_CC_0_INDEX);
    DL_TimerA_setCaptureCompareOutCtl(PWM_R_INST,
        DL_TIMER_CC_OCTL_INIT_VAL_LOW,
        DL_TIMER_CC_OCTL_INV_OUT_DISABLED,
        DL_TIMER_CC_OCTL_SRC_FUNCVAL,
        DL_TIMERA_CAPTURE_COMPARE_1_INDEX);
    DL_TimerA_setCaptCompUpdateMethod(PWM_R_INST,
        DL_TIMER_CC_UPDATE_METHOD_IMMEDIATE,
        DL_TIMERA_CAPTURE_COMPARE_1_INDEX);
    DL_TimerA_setCaptureCompareValue(PWM_R_INST, 4000,
        DL_TIMER_CC_1_INDEX);
    DL_TimerA_setCCPOutputDisabled(PWM_R_INST,
        DL_TIMER_CCP_DIS_OUT_LOW, DL_TIMER_CCP_DIS_OUT_LOW);
    DL_TimerA_enableClock(PWM_R_INST);
    DL_TimerA_setCCPDirection(PWM_R_INST, DL_TIMER_CC0_OUTPUT);
}

/* ── ADC motor current ── */
static const DL_ADC12_ClockConfig gADC_MOTORClockConfig = {
    .clockSel    = DL_ADC12_CLOCK_SYSOSC,
    .divideRatio = DL_ADC12_CLOCK_DIVIDE_1,
    .freqRange   = DL_ADC12_CLOCK_FREQ_RANGE_24_TO_32,
};

SYSCONFIG_WEAK void SYSCFG_DL_ADC_MOTOR_init(void)
{
    DL_ADC12_setClockConfig(ADC_MOTOR_INST,
        (DL_ADC12_ClockConfig *)&gADC_MOTORClockConfig);
    DL_ADC12_configConversionMem(ADC_MOTOR_INST, ADC_MOTOR_ADCMEM_0,
        DL_ADC12_INPUT_CHAN_0,
        DL_ADC12_REFERENCE_VOLTAGE_VDDA,
        DL_ADC12_SAMPLE_TIMER_SOURCE_SCOMP0,
        DL_ADC12_AVERAGING_MODE_DISABLED,
        DL_ADC12_BURN_OUT_SOURCE_DISABLED,
        DL_ADC12_TRIGGER_MODE_AUTO_NEXT,
        DL_ADC12_WINDOWS_COMP_MODE_DISABLED);
    DL_ADC12_setSampleTime0(ADC_MOTOR_INST, 8);
    DL_ADC12_enableConversions(ADC_MOTOR_INST);
}

/* Track sensor ADC (ADC1 MEM0, PA16/A1_1 via carrier flywire). */
SYSCONFIG_WEAK void SYSCFG_DL_ADC_TRACK_init(void)
{
    DL_ADC12_setClockConfig(ADC_TRACK_INST,
        (DL_ADC12_ClockConfig *)&gADC_MOTORClockConfig);
    DL_ADC12_initSingleSample(ADC_TRACK_INST,
        DL_ADC12_REPEAT_MODE_DISABLED,
        DL_ADC12_SAMPLING_SOURCE_AUTO,
        DL_ADC12_TRIG_SRC_SOFTWARE,
        DL_ADC12_SAMP_CONV_RES_12_BIT,
        DL_ADC12_SAMP_CONV_DATA_FORMAT_UNSIGNED);
    DL_ADC12_configConversionMem(ADC_TRACK_INST, ADC_TRACK_ADCMEM_0,
        DL_ADC12_INPUT_CHAN_1,
        DL_ADC12_REFERENCE_VOLTAGE_VDDA,
        DL_ADC12_SAMPLE_TIMER_SOURCE_SCOMP0,
        DL_ADC12_AVERAGING_MODE_DISABLED,
        DL_ADC12_BURN_OUT_SOURCE_DISABLED,
        DL_ADC12_TRIGGER_MODE_AUTO_NEXT,
        DL_ADC12_WINDOWS_COMP_MODE_DISABLED);
    DL_ADC12_setPowerDownMode(
        ADC_TRACK_INST, DL_ADC12_POWER_DOWN_MODE_MANUAL);
    DL_ADC12_setSampleTime0(ADC_TRACK_INST, 500);
    DL_ADC12_enableConversions(ADC_TRACK_INST);
}

/* ── SPI BMI088 (SPI0, 10 MHz: 80 MHz / ((1+3)*2)) ── */
static const DL_SPI_Config gSPI_BMI088_config = {
    .mode          = DL_SPI_MODE_CONTROLLER,
    .frameFormat   = DL_SPI_FRAME_FORMAT_MOTO4_POL0_PHA0,
    .parity        = DL_SPI_PARITY_NONE,
    .dataSize      = DL_SPI_DATA_SIZE_8,
    .bitOrder      = DL_SPI_BIT_ORDER_MSB_FIRST,
    .chipSelectPin = DL_SPI_CHIP_SELECT_0,
};

static const DL_SPI_ClockConfig gSPI_BMI088_clockConfig = {
    .clockSel    = DL_SPI_CLOCK_BUSCLK,
    .divideRatio = DL_SPI_CLOCK_DIVIDE_RATIO_1
};

SYSCONFIG_WEAK void SYSCFG_DL_SPI_BMI088_init(void)
{
    DL_SPI_setClockConfig(SPI_BMI088_INST,
        (DL_SPI_ClockConfig *)&gSPI_BMI088_clockConfig);
    DL_SPI_init(SPI_BMI088_INST,
        (DL_SPI_Config *)&gSPI_BMI088_config);
    /* outputBitRate = (80000000)/((1 + 3) * 2) = 10 MHz */
    DL_SPI_setBitRateSerialClockDivider(SPI_BMI088_INST, 3);
    DL_SPI_setFIFOThreshold(SPI_BMI088_INST,
        DL_SPI_RX_FIFO_LEVEL_1_2_FULL,
        DL_SPI_TX_FIFO_LEVEL_1_2_EMPTY);
    DL_SPI_enable(SPI_BMI088_INST);
}

/* ── MCAN0 (CANFD0, 80 MHz HFCLK, CAN-FD with BRS) ── */
static const DL_MCAN_ClockConfig gMCAN0ClockConf = {
    .clockSel = DL_MCAN_FCLK_HFCLK,
    .divider  = DL_MCAN_FCLK_DIV_1,
};

static const DL_MCAN_InitParams gMCAN0InitParams = {
    .fdMode            = true,
    .brsEnable         = true,
    .txpEnable         = false,
    .efbi              = false,
    .pxhddisable       = false,
    .darEnable         = false,
    .wkupReqEnable     = false,
    .autoWkupEnable    = false,
    .emulationEnable   = false,
    .tdcEnable         = false,
    .wdcPreload        = 255,
    .tdcConfig.tdcf    = 10,
    .tdcConfig.tdco    = 6,
};

static const DL_MCAN_ConfigParams gMCAN0ConfigParams = {
    .monEnable = false,
    .asmEnable = false,
    .tsPrescalar = 0,
    .tsSelect = 0,
    .timeoutSelect = DL_MCAN_TIMEOUT_SELECT_CONT,
    .timeoutPreload = 0,
    .timeoutCntEnable = false,
    .filterConfig.rrfe = 1,
    .filterConfig.rrfs = 1,
    .filterConfig.anfe = 2,
    .filterConfig.anfs = 0,
};

static const DL_MCAN_MsgRAMConfigParams gMCAN0MsgRAMConfigParams = {
    .flssa                = MCAN0_INST_MCAN_STD_ID_FILT_START_ADDR,
    .lss                  = MCAN0_INST_MCAN_STD_ID_FILTER_NUM,
    .flesa                = MCAN0_INST_MCAN_EXT_ID_FILT_START_ADDR,
    .lse                  = MCAN0_INST_MCAN_EXT_ID_FILTER_NUM,
    .txStartAddr          = MCAN0_INST_MCAN_TX_BUFF_START_ADDR,
    .txBufNum             = MCAN0_INST_MCAN_TX_BUFF_SIZE,
    .txFIFOSize           = 0,
    .txBufMode            = 0,
    .txBufElemSize        = DL_MCAN_ELEM_SIZE_64BYTES,
    .txEventFIFOStartAddr = MCAN0_INST_MCAN_TX_EVENT_START_ADDR,
    .txEventFIFOSize      = MCAN0_INST_MCAN_TX_EVENT_SIZE,
    .txEventFIFOWaterMark = 3,
    .rxFIFO0startAddr     = MCAN0_INST_MCAN_FIFO_0_START_ADDR,
    .rxFIFO0size          = MCAN0_INST_MCAN_FIFO_0_NUM,
    .rxFIFO0waterMark     = 3,
    .rxFIFO0OpMode        = 0,
    .rxFIFO1startAddr     = MCAN0_INST_MCAN_FIFO_1_START_ADDR,
    .rxFIFO1size          = MCAN0_INST_MCAN_FIFO_1_NUM,
    .rxFIFO1waterMark     = 3,
    .rxFIFO1OpMode        = 0,
    .rxBufStartAddr       = MCAN0_INST_MCAN_RX_BUFF_START_ADDR,
    .rxBufElemSize        = DL_MCAN_ELEM_SIZE_64BYTES,
    .rxFIFO0ElemSize      = DL_MCAN_ELEM_SIZE_64BYTES,
    .rxFIFO1ElemSize      = DL_MCAN_ELEM_SIZE_64BYTES,
};

static const DL_MCAN_BitTimingParams gMCAN0BitTimes = {
    .nomRatePrescalar   = 1,
    .nomTimeSeg1        = 33,
    .nomTimeSeg2        = 4,
    .nomSynchJumpWidth  = 4,
    .dataRatePrescalar  = 1,
    .dataTimeSeg1       = 16,
    .dataTimeSeg2       = 1,
    .dataSynchJumpWidth = 1,
};

SYSCONFIG_WEAK void SYSCFG_DL_MCAN0_init(void)
{
    DL_MCAN_RevisionId revid_MCAN0;
    DL_MCAN_StdMsgIDFilterElement stdFilter;
    uint32_t waitLimit;

    DL_MCAN_enableModuleClock(MCAN0_INST);
    DL_MCAN_setClockConfig(MCAN0_INST, (DL_MCAN_ClockConfig *)&gMCAN0ClockConf);
    DL_MCAN_getRevisionId(MCAN0_INST, &revid_MCAN0);

    /* Wait for Memory initialization to be completed. */
    waitLimit = 1000000U;
    while (false == DL_MCAN_isMemInitDone(MCAN0_INST)) {
        if (waitLimit-- == 0U) {
            knx_mspm0_boot_error |= KNX_MSPM0_BOOT_ERR_MCAN_MEM_INIT;
            return;
        }
    }

    /* Put MCAN in SW initialization mode. */
    DL_MCAN_setOpMode(MCAN0_INST, DL_MCAN_OPERATION_MODE_SW_INIT);
    if (!knx_wait_mcan_opmode(MCAN0_INST,
                              DL_MCAN_OPERATION_MODE_SW_INIT,
                              1000000U)) {
        knx_mspm0_boot_error |= KNX_MSPM0_BOOT_ERR_MCAN_SW_INIT;
        return;
    }

    /* Initialize MCAN module. */
    DL_MCAN_init(MCAN0_INST, (DL_MCAN_InitParams *)&gMCAN0InitParams);
    DL_MCAN_config(MCAN0_INST, (DL_MCAN_ConfigParams *)&gMCAN0ConfigParams);

    /* Configure Bit timings. */
    DL_MCAN_setBitTime(MCAN0_INST, (DL_MCAN_BitTimingParams *)&gMCAN0BitTimes);

    /* Configure Message RAM Sections */
    DL_MCAN_msgRAMConfig(MCAN0_INST,
        (DL_MCAN_MsgRAMConfigParams *)&gMCAN0MsgRAMConfigParams);

    /* Set Extended ID Mask. */
    DL_MCAN_setExtIDAndMask(MCAN0_INST, MCAN0_INST_MCAN_EXT_ID_AND_MASK);

    stdFilter.sfid1 = 0x000U;
    stdFilter.sfid2 = 0x7FFU;
    stdFilter.sfec = 1U;
    stdFilter.sft = 0U;
    DL_MCAN_addStdMsgIDFilter(MCAN0_INST, 0U, &stdFilter);

    /* Normal bus operation. Do not enable internal loopback here. */
    DL_MCAN_lpbkModeEnable(MCAN0_INST, DL_MCAN_LPBK_MODE_INTERNAL, false);

    /* Take MCAN out of the SW initialization mode */
    DL_MCAN_setOpMode(MCAN0_INST, DL_MCAN_OPERATION_MODE_NORMAL);
    if (!knx_wait_mcan_opmode(MCAN0_INST,
                              DL_MCAN_OPERATION_MODE_NORMAL,
                              1000000U)) {
        knx_mspm0_boot_error |= KNX_MSPM0_BOOT_ERR_MCAN_NORMAL;
    }
}
