/*
 *  ============ ti_msp_dl_config.h ============
 *  Generated by SysConfig, manually patched for 80 MHz + GPIO inputs.
 *  Includes all peripherals: QEI, UART, PWM, ADC, SPI BMI088, MCAN, GPIO.
 */
#ifndef ti_msp_dl_config_h
#define ti_msp_dl_config_h

#define CONFIG_MSPM0G350X
#define CONFIG_MSPM0G3507

#if defined(__ti_version__) || defined(__TI_COMPILER_VERSION__)
#define SYSCONFIG_WEAK __attribute__((weak))
#elif defined(__IAR_SYSTEMS_ICC__)
#define SYSCONFIG_WEAK __weak
#elif defined(__GNUC__)
#define SYSCONFIG_WEAK __attribute__((weak))
#endif

#include <ti/devices/msp/msp.h>
#include <ti/driverlib/driverlib.h>
#include <ti/driverlib/m0p/dl_core.h>

#ifdef __cplusplus
extern "C" {
#endif

/* clang-format off */

#define POWER_STARTUP_DELAY                                                (16)

#define GPIO_HFXT_PORT                                                     GPIOA
#define GPIO_HFXIN_PIN                                             DL_GPIO_PIN_5
#define GPIO_HFXIN_IOMUX                                         (IOMUX_PINCM10)
#define GPIO_HFXOUT_PIN                                            DL_GPIO_PIN_6
#define GPIO_HFXOUT_IOMUX                                        (IOMUX_PINCM11)
#define CPUCLK_FREQ                                                     80000000

/* ── QEI_LEFT (TIMG8, PA21=CCP0, PA22=CCP1) ── */
#define QEI_LEFT_INST                                                      TIMG8
#define QEI_LEFT_INST_IRQHandler                                TIMG8_IRQHandler
#define QEI_LEFT_INST_INT_IRQN                                  (TIMG8_INT_IRQn)
#define GPIO_QEI_LEFT_PHA_PORT                                             GPIOA
#define GPIO_QEI_LEFT_PHA_PIN                                     DL_GPIO_PIN_21
#define GPIO_QEI_LEFT_PHA_IOMUX                                  (IOMUX_PINCM46)
#define GPIO_QEI_LEFT_PHA_IOMUX_FUNC                 IOMUX_PINCM46_PF_TIMG8_CCP0
#define GPIO_QEI_LEFT_PHB_PORT                                             GPIOA
#define GPIO_QEI_LEFT_PHB_PIN                                     DL_GPIO_PIN_22
#define GPIO_QEI_LEFT_PHB_IOMUX                                  (IOMUX_PINCM47)
#define GPIO_QEI_LEFT_PHB_IOMUX_FUNC                 IOMUX_PINCM47_PF_TIMG8_CCP1

/* ── UART_DEBUG (UART3, PB2=TX, PB3=RX, 921600 @ 80 MHz) ── */
#define UART_DEBUG_INST                                                    UART3
#define UART_DEBUG_INST_FREQUENCY                                       80000000
#define UART_DEBUG_INST_IRQHandler                              UART3_IRQHandler
#define UART_DEBUG_INST_INT_IRQN                                  UART3_INT_IRQn
#define GPIO_UART_DEBUG_RX_PORT                                            GPIOB
#define GPIO_UART_DEBUG_TX_PORT                                            GPIOB
#define GPIO_UART_DEBUG_RX_PIN                                     DL_GPIO_PIN_3
#define GPIO_UART_DEBUG_TX_PIN                                     DL_GPIO_PIN_2
#define GPIO_UART_DEBUG_IOMUX_RX                                 (IOMUX_PINCM16)
#define GPIO_UART_DEBUG_IOMUX_TX                                 (IOMUX_PINCM15)
#define GPIO_UART_DEBUG_IOMUX_RX_FUNC                  IOMUX_PINCM16_PF_UART3_RX
#define GPIO_UART_DEBUG_IOMUX_TX_FUNC                  IOMUX_PINCM15_PF_UART3_TX
#define UART_DEBUG_BAUD_RATE                                           (921600)
#define UART_DEBUG_IBRD_80_MHZ_921600_BAUD                              (5)
#define UART_DEBUG_FBRD_80_MHZ_921600_BAUD                             (27)

/* ── PWM_L (TIMA0, CC0=PA0, CC1=PA1, 20 kHz) ── */
#define PWM_L_INST                                                        TIMA0
#define PWM_L_INST_IRQHandler                                  TIMA0_IRQHandler
#define PWM_L_INST_INT_IRQN                                    (TIMA0_INT_IRQn)
#define PWM_L_INST_CLK_FREQ                                             80000000
#define GPIO_PWM_L_C0_PORT                                               GPIOA
#define GPIO_PWM_L_C0_PIN                                       DL_GPIO_PIN_0
#define GPIO_PWM_L_C0_IOMUX                                     (IOMUX_PINCM1)
#define GPIO_PWM_L_C0_IOMUX_FUNC                   IOMUX_PINCM1_PF_TIMA0_CCP0
#define GPIO_PWM_L_C0_IDX                                    DL_TIMER_CC_0_INDEX
#define GPIO_PWM_L_C1_PORT                                               GPIOA
#define GPIO_PWM_L_C1_PIN                                       DL_GPIO_PIN_1
#define GPIO_PWM_L_C1_IOMUX                                     (IOMUX_PINCM2)
#define GPIO_PWM_L_C1_IOMUX_FUNC                   IOMUX_PINCM2_PF_TIMA0_CCP1
#define GPIO_PWM_L_C1_IDX                                    DL_TIMER_CC_1_INDEX

/* ── PWM_R (TIMA1, CC0=PA15, CC1=PA16, 20 kHz) ── */
#define PWM_R_INST                                                        TIMA1
#define PWM_R_INST_IRQHandler                                  TIMA1_IRQHandler
#define PWM_R_INST_INT_IRQN                                    (TIMA1_INT_IRQn)
#define PWM_R_INST_CLK_FREQ                                             80000000
#define GPIO_PWM_R_C0_PORT                                               GPIOA
#define GPIO_PWM_R_C0_PIN                                      DL_GPIO_PIN_15
#define GPIO_PWM_R_C0_IOMUX                                    (IOMUX_PINCM37)
#define GPIO_PWM_R_C0_IOMUX_FUNC                  IOMUX_PINCM37_PF_TIMA1_CCP0
#define GPIO_PWM_R_C0_IDX                                    DL_TIMER_CC_0_INDEX
#define GPIO_PWM_R_C1_PORT                                               GPIOA
#define GPIO_PWM_R_C1_PIN                                      DL_GPIO_PIN_16
#define GPIO_PWM_R_C1_IOMUX                                    (IOMUX_PINCM38)
#define GPIO_PWM_R_C1_IOMUX_FUNC                  IOMUX_PINCM38_PF_TIMA1_CCP1
#define GPIO_PWM_R_C1_IDX                                    DL_TIMER_CC_1_INDEX

/* ── ADC_MOTOR (ADC0, PA27) ── */
#define ADC_MOTOR_INST                                                     ADC0
#define ADC_MOTOR_INST_IRQHandler                               ADC0_IRQHandler
#define ADC_MOTOR_INST_INT_IRQN                                 (ADC0_INT_IRQn)
#define ADC_MOTOR_ADCMEM_0                                   DL_ADC12_MEM_IDX_0
#define ADC_MOTOR_ADCMEM_0_REF                  DL_ADC12_REFERENCE_VOLTAGE_VDDA
#define ADC_MOTOR_ADCMEM_0_REF_VOLTAGE_V                               (3.3f)
#define GPIO_ADC_MOTOR_C0_PORT                                           GPIOA
#define GPIO_ADC_MOTOR_C0_PIN                                   DL_GPIO_PIN_27
#define GPIO_ADC_MOTOR_C0_IOMUX                                  (IOMUX_PINCM60)

/* ── SPI_BMI088 (SPI0, SCLK=PA11, PICO=PA14, POCI=PA10, CS0=PB25) ── */
#define SPI_BMI088_INST                                                    SPI0
#define SPI_BMI088_INST_IRQHandler                              SPI0_IRQHandler
#define SPI_BMI088_INST_INT_IRQN                                  SPI0_INT_IRQn
#define GPIO_SPI_BMI088_PICO_PORT                                         GPIOA
#define GPIO_SPI_BMI088_PICO_PIN                                 DL_GPIO_PIN_14
#define GPIO_SPI_BMI088_IOMUX_PICO                              (IOMUX_PINCM36)
#define GPIO_SPI_BMI088_IOMUX_PICO_FUNC              IOMUX_PINCM36_PF_SPI0_PICO
#define GPIO_SPI_BMI088_POCI_PORT                                         GPIOA
#define GPIO_SPI_BMI088_POCI_PIN                                 DL_GPIO_PIN_10
#define GPIO_SPI_BMI088_IOMUX_POCI                              (IOMUX_PINCM21)
#define GPIO_SPI_BMI088_IOMUX_POCI_FUNC              IOMUX_PINCM21_PF_SPI0_POCI
#define GPIO_SPI_BMI088_SCLK_PORT                                         GPIOA
#define GPIO_SPI_BMI088_SCLK_PIN                                 DL_GPIO_PIN_11
#define GPIO_SPI_BMI088_IOMUX_SCLK                              (IOMUX_PINCM22)
#define GPIO_SPI_BMI088_IOMUX_SCLK_FUNC              IOMUX_PINCM22_PF_SPI0_SCLK
#define GPIO_SPI_BMI088_CS0_PORT                                          GPIOB
#define GPIO_SPI_BMI088_CS0_PIN                                  DL_GPIO_PIN_25
#define GPIO_SPI_BMI088_IOMUX_CS0                               (IOMUX_PINCM56)
#define GPIO_SPI_BMI088_IOMUX_CS0_FUNC                IOMUX_PINCM56_PF_SPI0_CS0

/* ── MCAN0 (CANFD0, TX=PA12, RX=PA13) ── */
#define MCAN0_INST                                                        CANFD0
#define MCAN0_INST_IRQHandler                                CANFD0_IRQHandler
#define MCAN0_INST_INT_IRQN                                  (CANFD0_INT_IRQn)
#define GPIO_MCAN0_CAN_TX_PORT                                             GPIOA
#define GPIO_MCAN0_CAN_TX_PIN                                     DL_GPIO_PIN_12
#define GPIO_MCAN0_IOMUX_CAN_TX                                  (IOMUX_PINCM34)
#define GPIO_MCAN0_IOMUX_CAN_TX_FUNC               IOMUX_PINCM34_PF_CANFD0_CANTX
#define GPIO_MCAN0_CAN_RX_PORT                                             GPIOA
#define GPIO_MCAN0_CAN_RX_PIN                                     DL_GPIO_PIN_13
#define GPIO_MCAN0_IOMUX_CAN_RX                                  (IOMUX_PINCM35)
#define GPIO_MCAN0_IOMUX_CAN_RX_FUNC               IOMUX_PINCM35_PF_CANFD0_CANRX

/* MCAN0 MCAN RAM configuration */
#define MCAN0_INST_MCAN_STD_ID_FILT_START_ADDR     (0)
#define MCAN0_INST_MCAN_STD_ID_FILTER_NUM          (1)
#define MCAN0_INST_MCAN_EXT_ID_FILT_START_ADDR     (48)
#define MCAN0_INST_MCAN_EXT_ID_FILTER_NUM          (1)
#define MCAN0_INST_MCAN_TX_BUFF_START_ADDR         (148)
#define MCAN0_INST_MCAN_TX_BUFF_SIZE               (2)
#define MCAN0_INST_MCAN_FIFO_1_START_ADDR          (192)
#define MCAN0_INST_MCAN_FIFO_1_NUM                 (2)
#define MCAN0_INST_MCAN_TX_EVENT_START_ADDR        (164)
#define MCAN0_INST_MCAN_TX_EVENT_SIZE              (2)
#define MCAN0_INST_MCAN_EXT_ID_AND_MASK            (0x1FFFFFFFU)
#define MCAN0_INST_MCAN_RX_BUFF_START_ADDR         (208)
#define MCAN0_INST_MCAN_FIFO_0_START_ADDR          (172)
#define MCAN0_INST_MCAN_FIFO_0_NUM                 (3)

/* ── BMI chip-select GPIO outputs (active-low) ── */
#define BMI_CS0_PORT                                                     (GPIOA)
#define BMI_CS0_CS0_PIN_PIN                                     (DL_GPIO_PIN_25)
#define BMI_CS0_CS0_PIN_IOMUX                                    (IOMUX_PINCM55)
#define BMI_CS1_PORT                                                     (GPIOA)
#define BMI_CS1_CS1_PIN_PIN                                     (DL_GPIO_PIN_24)
#define BMI_CS1_CS1_PIN_IOMUX                                    (IOMUX_PINCM54)

/* ── Track sensor MUX select GPIO outputs ── */
#define TRK_AD0_PORT                                                     (GPIOB)
#define TRK_AD0_AD0_PIN_PIN                                      (DL_GPIO_PIN_4)
#define TRK_AD0_AD0_PIN_IOMUX                                    (IOMUX_PINCM17)
#define TRK_AD1_PORT                                                     (GPIOB)
#define TRK_AD1_AD1_PIN_PIN                                      (DL_GPIO_PIN_5)
#define TRK_AD1_AD1_PIN_IOMUX                                    (IOMUX_PINCM18)
#define TRK_AD2_PORT                                                     (GPIOB)
#define TRK_AD2_AD2_PIN_PIN                                      (DL_GPIO_PIN_7)
#define TRK_AD2_AD2_PIN_IOMUX                                    (IOMUX_PINCM24)

/* ── Motor PHASE GPIOs ── */
#define MOTOR_L_PH_PORT                                                  (GPIOA)
#define MOTOR_L_PH_ML_PHASE_PIN                                (DL_GPIO_PIN_7)
#define MOTOR_L_PH_ML_PHASE_IOMUX                              (IOMUX_PINCM14)
#define MOTOR_R_PH_PORT                                                  (GPIOA)
#define MOTOR_R_PH_MR_PHASE_PIN                                (DL_GPIO_PIN_2)
#define MOTOR_R_PH_MR_PHASE_IOMUX                               (IOMUX_PINCM7)

/* ── LED ── */
#define LED0_PORT                                                        (GPIOB)
#define LED0_LED0_PIN_PIN                                       (DL_GPIO_PIN_16)
#define LED0_LED0_PIN_IOMUX                                      (IOMUX_PINCM33)
#define LED1_PORT                                                        (GPIOB)
#define LED1_LED1_PIN_PIN                                       (DL_GPIO_PIN_19)
#define LED1_LED1_PIN_IOMUX                                      (IOMUX_PINCM45)
#define LED2_PORT                                                        (GPIOB)
#define LED2_LED2_PIN_PIN                                       (DL_GPIO_PIN_21)
#define LED2_LED2_PIN_IOMUX                                      (IOMUX_PINCM49)

/* ── KEY (digital input) ── */
#define KEY0_PORT                                                        (GPIOB)
#define KEY0_KEY0_PIN_PIN                                       (DL_GPIO_PIN_23)
#define KEY0_KEY0_PIN_IOMUX                                      (IOMUX_PINCM51)
#define KEY1_PORT                                                        (GPIOB)
#define KEY1_KEY1_PIN_PIN                                       (DL_GPIO_PIN_27)
#define KEY1_KEY1_PIN_IOMUX                                      (IOMUX_PINCM58)

/* ── BEEP ── */
#define BEEP_PORT                                                        (GPIOB)
#define BEEP_BEEP0_PIN_PIN                                       (DL_GPIO_PIN_6)
#define BEEP_BEEP0_PIN_IOMUX                                     (IOMUX_PINCM23)

/* ── Right Encoder GPIO ── */
#define ENC_RA_PORT                                                      (GPIOA)
#define ENC_RA_ENC_RA_PIN_PIN                                    (DL_GPIO_PIN_8)
#define ENC_RA_ENC_RA_PIN_IOMUX                                  (IOMUX_PINCM19)
#define ENC_RB_PORT                                                      (GPIOA)
#define ENC_RB_ENC_RB_PIN_PIN                                    (DL_GPIO_PIN_9)
#define ENC_RB_ENC_RB_PIN_IOMUX                                  (IOMUX_PINCM20)

/* clang-format on */

void SYSCFG_DL_init(void);
void SYSCFG_DL_initPower(void);
void SYSCFG_DL_GPIO_init(void);
void SYSCFG_DL_SYSCTL_init(void);
void SYSCFG_DL_QEI_LEFT_init(void);
void SYSCFG_DL_UART_DEBUG_init(void);
void SYSCFG_DL_PWM_L_init(void);
void SYSCFG_DL_PWM_R_init(void);
void SYSCFG_DL_ADC_MOTOR_init(void);
void SYSCFG_DL_SPI_BMI088_init(void);
void SYSCFG_DL_MCAN0_init(void);

bool SYSCFG_DL_saveConfiguration(void);
bool SYSCFG_DL_restoreConfiguration(void);

extern volatile uint32_t knx_mspm0_boot_stage;
extern volatile uint32_t knx_mspm0_boot_error;

#ifdef __cplusplus
}
#endif

#endif /* ti_msp_dl_config_h */
