#include "knx_params.h"
#include "knexus_config.h"

knx_params_t g_knx_params = {
    .mech = {
        .wheel_radius_m = KNEXUS_WHEEL_RADIUS_M_DEFAULT,
        .wheel_base_m = KNEXUS_WHEEL_BASE_M_DEFAULT,
        .track_width_m = KNEXUS_TRACK_WIDTH_M_DEFAULT,
        .body_mass_kg = KNEXUS_BODY_MASS_KG_DEFAULT,
        .body_inertia_kgm2 = KNEXUS_BODY_INERTIA_KGM2_DEFAULT,
        .body_pitch_inertia_kgm2 = KNEXUS_BODY_INERTIA_KGM2_DEFAULT,
        .com_height_m = KNEXUS_COM_HEIGHT_M_DEFAULT,
        .motor_torque_constant_nm_per_a = KNEXUS_MOTOR_TORQUE_KT_DEFAULT,
        .motor_gear_ratio = KNEXUS_MOTOR_GEAR_RATIO_DEFAULT,
        .motor_torque_efficiency = KNEXUS_MOTOR_EFFICIENCY_DEFAULT,
    },
    .safety = {
        .max_tilt_deg = KNEXUS_SAFETY_MAX_TILT_DEG_DEFAULT,
        .max_current_a = KNEXUS_SAFETY_MAX_CURRENT_A_DEFAULT,
        .max_speed_mps = KNEXUS_SAFETY_MAX_SPEED_MPS_DEFAULT,
        .imu_timeout_ms = KNEXUS_SAFETY_IMU_TIMEOUT_MS_DEFAULT,
        .warmup_temp_tolerance_c = KNEXUS_SAFETY_WARMUP_TOLERANCE_C_DEFAULT,
        .warmup_stable_ms = KNEXUS_SAFETY_WARMUP_STABLE_MS_DEFAULT,
    },
    .drive = {
        .drive_en = true,
        .left_cmd_sign = 1.0f,
        .right_cmd_sign = 1.0f,
        .left_feedback_sign = 1.0f,
        .right_feedback_sign = 1.0f,
        .angular_feedback_sign = 1.0f,
        .max_linear_speed_mps = KNEXUS_DRIVE_MAX_LINEAR_MPS_DEFAULT,
        .max_angular_speed_radps = KNEXUS_DRIVE_MAX_ANGULAR_RADPS_DEFAULT,
        .max_linear_accel_mps2 = KNEXUS_DRIVE_MAX_LINEAR_ACCEL_MPS2_DEFAULT,
        .max_angular_accel_radps2 = KNEXUS_DRIVE_MAX_ANGULAR_ACCEL_RADPS2_DEFAULT,
        .command_timeout_ms = KNEXUS_DRIVE_COMMAND_TIMEOUT_MS_DEFAULT,
        .position_pid = {
            .kp = KNEXUS_POSITION_KP_DEFAULT,
            .ki = KNEXUS_POSITION_KI_DEFAULT,
            .kd = KNEXUS_POSITION_KD_DEFAULT,
            .max_out = KNEXUS_POSITION_MAX_OUT_DEFAULT,
            .integral_limit = KNEXUS_POSITION_I_LIMIT_DEFAULT,
            .deadband = 0.0f,
        },
        .angle_pid = {
            .kp = KNEXUS_ANGLE_KP_DEFAULT,
            .ki = KNEXUS_ANGLE_KI_DEFAULT,
            .kd = KNEXUS_ANGLE_KD_DEFAULT,
            .max_out = KNEXUS_ANGLE_MAX_OUT_DEFAULT,
            .integral_limit = KNEXUS_ANGLE_I_LIMIT_DEFAULT,
            .deadband = 0.0f,
        },
        .linear_speed_pid = {
            .kp = KNEXUS_LINEAR_SPEED_KP_DEFAULT,
            .ki = KNEXUS_LINEAR_SPEED_KI_DEFAULT,
            .kd = KNEXUS_LINEAR_SPEED_KD_DEFAULT,
            .max_out = KNEXUS_LINEAR_SPEED_MAX_OUT_DEFAULT,
            .integral_limit = KNEXUS_LINEAR_SPEED_I_LIMIT_DEFAULT,
            .deadband = 0.0f,
        },
        .angular_speed_pid = {
            .kp = KNEXUS_ANGULAR_SPEED_KP_DEFAULT,
            .ki = KNEXUS_ANGULAR_SPEED_KI_DEFAULT,
            .kd = KNEXUS_ANGULAR_SPEED_KD_DEFAULT,
            .max_out = KNEXUS_ANGULAR_SPEED_MAX_OUT_DEFAULT,
            .integral_limit = KNEXUS_ANGULAR_SPEED_I_LIMIT_DEFAULT,
            .deadband = 0.0f,
        },
    },
};
