#ifndef KNX_TARGET_CONFIG_H
#define KNX_TARGET_CONFIG_H

/*
 * Target configuration — resolved from board config.
 * Do not edit this file directly; define symbols in board/knx_board_config.h.
 */

#include "knx_board_config.h"

#if defined(KNX_TARGET_STM32H743IIT6)
  #define KNX_PLATFORM_STM32   1
#elif defined(KNX_TARGET_MSPM0)
  #define KNX_PLATFORM_MSPM0   1
#else
  #error "No target defined in knx_board_config.h"
#endif

#endif /* KNX_TARGET_CONFIG_H */
