#include "knx_params.h"

knx_params_t g_knx_params = {
    .mech = {
        .wheel_radius_m = 0.0325f,
        .wheel_base_m = 0.1600f,
        .track_width_m = 0.1600f,
        .body_mass_kg = 0.2152f,
        .body_inertia_kgm2 = 0.00064386311f,
        .body_pitch_inertia_kgm2 = 0.00064386311f,
        .com_height_m = 0.05288f,
        .motor_torque_constant_nm_per_a = 0.00984f,
        .motor_gear_ratio = 28.0f,
        .motor_torque_efficiency = 0.65f,
    },
    .safety = {
        .max_tilt_deg = 65.0f,
        .max_current_a = 4.2f,
        .max_speed_mps = 8.0f,
        .imu_timeout_ms = 50U,
        .warmup_temp_tolerance_c = 0.8f,
        .warmup_stable_ms = 500U,
    },
    .drive = {
        .drive_en = true,
        .left_cmd_sign = 1.0f,
        .right_cmd_sign = 1.0f,
        .left_feedback_sign = 1.0f,
        .right_feedback_sign = 1.0f,
        .angular_feedback_sign = 1.0f,
        .max_linear_speed_mps = 1.0f,
        .max_angular_speed_radps = 4.0f,
        .max_linear_accel_mps2 = 1.5f,
        .max_angular_accel_radps2 = 6.0f,
        .command_timeout_ms = 200U,
        .position_pid = {
            .kp = 1.0f,
            .ki = 0.03f,
            .kd = 0.1f,
            .max_out = 0.8f,
            .integral_limit = 0.3f,
            .deadband = 0.0f,
        },
        .angle_pid = {
            .kp = 0.005f,
            .ki = 0.0005f,
            .kd = 0.004f,
            .max_out = 2.0f,
            .integral_limit = 0.3f,
            .deadband = 0.0f,
        },
        .linear_speed_pid = {
            .kp = 0.8f,
            .ki = 0.0f,
            .kd = 0.0f,
            .max_out = 1.0f,
            .integral_limit = 0.3f,
            .deadband = 0.0f,
        },
        .angular_speed_pid = {
            .kp = 0.8f,
            .ki = 0.0f,
            .kd = 0.0f,
            .max_out = 4.0f,
            .integral_limit = 0.5f,
            .deadband = 0.0f,
        },
    },
};
