/* Auto-generated by export_track_tinycnn_c.py */
/* DO NOT EDIT MANUALLY */

#include "track_tinycnn.h"
#include <math.h>
#include <string.h>

/* 外部权重声明 (定义在 track_tinycnn_weights.c) */
extern const float conv1_weight[TRACK_NN_FILTERS][TRACK_NN_COLS][TRACK_NN_KERNEL];
extern const float conv1_bias[TRACK_NN_FILTERS];
extern const float conv2_weight[TRACK_NN_FILTERS][TRACK_NN_FILTERS][TRACK_NN_KERNEL];
extern const float conv2_bias[TRACK_NN_FILTERS];
extern const float fc_weight[TRACK_NN_CLASSES][TRACK_NN_FILTERS];
extern const float fc_bias[TRACK_NN_CLASSES];
extern const char *track_tinycnn_class_names[TRACK_NN_CLASSES];

/* 特征缓冲区 - static 避免栈溢出，适合嵌入式 */
static float buf_a[TRACK_NN_FILTERS][TRACK_NN_ROWS];  /* 中间特征 */
static float buf_b[TRACK_NN_FILTERS][TRACK_NN_ROWS];  /* 中间特征 */

/* 归一化输入缓冲区 */
static float norm_input[TRACK_NN_COLS][TRACK_NN_ROWS];

/*
 * Conv1D 实现 (padding=2, stride=1, no dilation)
 * input:  [in_ch][length]
 * output: [out_ch][length]
 * weight: [out_ch][in_ch][kernel]
 * bias:   [out_ch]
 */
static void conv1d_relu(
    const float *input,   /* [in_ch][length] */
    int in_ch, int length,
    const float *weight,  /* [out_ch][in_ch][kernel] */
    const float *bias,    /* [out_ch] */
    int out_ch, int kernel, int padding,
    float *output         /* [out_ch][length] */
) {
    for (int oc = 0; oc < out_ch; oc++) {
        for (int i = 0; i < length; i++) {
            float sum = bias[oc];
            for (int ic = 0; ic < in_ch; ic++) {
                for (int k = 0; k < kernel; k++) {
                    int idx = i + k - padding;
                    if (idx >= 0 && idx < length) {
                        /* weight layout: [out_ch][in_ch][kernel] */
                        int w_idx = oc * in_ch * kernel + ic * kernel + k;
                        int in_idx = ic * length + idx;
                        sum += input[in_idx] * weight[w_idx];
                    }
                }
            }
            /* ReLU */
            output[oc * length + i] = sum > 0.0f ? sum : 0.0f;
        }
    }
}

/*
 * Global Average Pooling
 * input:  [channels][length]
 * output: [channels]
 */
static void global_avg_pool(const float *input, int channels, int length, float *output) {
    for (int c = 0; c < channels; c++) {
        float sum = 0.0f;
        for (int i = 0; i < length; i++) {
            sum += input[c * length + i];
        }
        output[c] = sum / (float)length;
    }
}

/*
 * 全连接层 + softmax
 * input:  [in_features]
 * weight: [out_features][in_features]
 * bias:   [out_features]
 * output: logits[out_features], probs[out_features]
 */
static void fc_softmax(const float *input, int in_features,
                        const float *weight, const float *bias, int out_features,
                        float *logits, float *probs) {
    /* 计算 logits */
    float max_logit = -1e30f;
    for (int i = 0; i < out_features; i++) {
        float sum = bias[i];
        for (int j = 0; j < in_features; j++) {
            sum += input[j] * weight[i * in_features + j];
        }
        logits[i] = sum;
        if (sum > max_logit) max_logit = sum;
    }

    /* 数值稳定的 softmax */
    float exp_sum = 0.0f;
    for (int i = 0; i < out_features; i++) {
        probs[i] = expf(logits[i] - max_logit);
        exp_sum += probs[i];
    }
    for (int i = 0; i < out_features; i++) {
        probs[i] /= exp_sum;
    }
}

/*
 * 主推理函数
 */
void track_tinycnn_predict_u8(
    const uint8_t sample[TRACK_NN_ROWS][TRACK_NN_COLS],
    track_tinycnn_result_t *result
) {
    /* Step 1: 归一化输入 uint8 -> float32 [0, 1]
     * 并转置为 [cols=8][rows=64] (即 [channels][length]) */
    for (int r = 0; r < TRACK_NN_ROWS; r++) {
        for (int c = 0; c < TRACK_NN_COLS; c++) {
            norm_input[c][r] = (float)sample[r][c] / 255.0f;
        }
    }

    /* Step 2: Conv1 + ReLU */
    conv1d_relu(
        &norm_input[0][0],
        TRACK_NN_COLS, TRACK_NN_ROWS,   /* in_ch=8, length=64 */
        &conv1_weight[0][0][0], conv1_bias,
        TRACK_NN_FILTERS, TRACK_NN_KERNEL, 2,  /* out_ch=8, kernel=5, padding=2 */
        &buf_a[0][0]
    );

    /* Step 3: Conv2 + ReLU */
    conv1d_relu(
        &buf_a[0][0],
        TRACK_NN_FILTERS, TRACK_NN_ROWS,  /* in_ch=8, length=64 */
        &conv2_weight[0][0][0], conv2_bias,
        TRACK_NN_FILTERS, TRACK_NN_KERNEL, 2,  /* out_ch=8, kernel=5, padding=2 */
        &buf_b[0][0]
    );

    /* Step 4: Global Average Pooling -> [8] */
    float gap[TRACK_NN_FILTERS];
    global_avg_pool(&buf_b[0][0], TRACK_NN_FILTERS, TRACK_NN_ROWS, gap);

    /* Step 5: FC + Softmax */
    fc_softmax(gap, TRACK_NN_FILTERS,
               &fc_weight[0][0], fc_bias, TRACK_NN_CLASSES,
               result->logits, result->probs);

    /* Step 6: 找最大概率 */
    result->pred_class = 0;
    result->confidence = result->probs[0];
    for (uint8_t i = 1; i < TRACK_NN_CLASSES; i++) {
        if (result->probs[i] > result->confidence) {
            result->confidence = result->probs[i];
            result->pred_class = i;
        }
    }
}

const char *track_tinycnn_class_name(uint8_t class_id) {
    if (class_id < TRACK_NN_CLASSES) {
        return track_tinycnn_class_names[class_id];
    }
    return "unknown";
}
