/* Auto-generated by export_track_tinycnn_c.py */
/* DO NOT EDIT MANUALLY */

#ifndef TRACK_TINYCNN_H
#define TRACK_TINYCNN_H

#include <stdint.h>

#define TRACK_NN_ROWS 64
#define TRACK_NN_COLS 8
#define TRACK_NN_CLASSES 2
#define TRACK_NN_FILTERS 8
#define TRACK_NN_KERNEL 5

typedef struct {
    uint8_t pred_class;
    float confidence;
    float logits[TRACK_NN_CLASSES];
    float probs[TRACK_NN_CLASSES];
} track_tinycnn_result_t;

/**
 * @brief 用训练好的模型对 64×8 灰度样本做推理。
 * @param sample  64×8 uint8 灰度矩阵 (0=白底, 255=黑线)
 * @param result  输出结果 (pred_class, confidence, logits, probs)
 */
void track_tinycnn_predict_u8(
    const uint8_t sample[TRACK_NN_ROWS][TRACK_NN_COLS],
    track_tinycnn_result_t *result
);

/**
 * @brief 获取类别名称。
 * @param class_id  类别编号
 * @return 类别名称字符串，无效编号返回 "unknown"
 */
const char *track_tinycnn_class_name(uint8_t class_id);

#endif /* TRACK_TINYCNN_H */
